# -*- coding: utf-8 -*-
"""reducer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c-__WfiBO86ng2_dOgBxE7HEeqFLGZnA
"""

#! /usr/bin/env python3

"""
import sys
token=None
currentToken=None
currentCounter=0
for line in sys.stdin:
    Line_Data=line.strip()
    Line_Data=Line_Data.lower()
    token,count=Line_Data.split('\t',1)
    try:
      count=int(count)
    except ValueError:
      continue
    if currentToken==token:
        currentCounter+=count
    else:
        if currentToken:
            print("%s\t%s" % (currentToken,currentCounter))
        currentCounter=count
        currentToken=token
## Final Token
if currentToken==token:
    print("%s\t%s" % (currentToken,currentCounter))
 """

#!pip install numpy
#import numpy as np
import sys

Reduced={}
for line in sys.stdin:
	#line=line.strip()
	#ID_String,Value=line.split() # (ID,count)=line.split('\t', 1)
	(Key,Value)=line.strip().split() # ID_String
	Key_Day=int(Key)
	if Key_Day not in Reduced:
		Reduced[Key_Day]=list()
		Reduced[Key_Day].append(float(Value)) # append(Value) # int(Value) # float
	else:
		Reduced[Key_Day].append(float(Value)) # append(int(Value)) # float
	   
for Key_Day in Reduced:
	Keys_Values=Reduced.get(Key_Day)
	Min=min(Keys_Values)
	print('Daily Min: '+str(Key_Day),Min)
	Max=max(Keys_Values)
	print("Daily Max: "+str(Key_Day),Max)
	#FuncMean=lambda Keys_Values: reduce(lambda x,y: x+y,Keys_Values)/float(len(Keys_Values)) #! int # stackoverflow.com/a/9595150
	Mean=sum(Keys_Values)/len(Keys_Values) # float(len(Keys_Values)) # int # float
	print("Daily Mean: "+str(Key_Day),Mean)
	#StDev=np.std(Keys_Values) # permission granted for numpy?? @ learn.london.ac.uk/mod/forum/discuss.php?d=12951#p36300
	## Functional Code inspired by rosettacode.org/wiki/Cumulative_standard_deviation#Python:_In_a_couple_of_.27functional.27_lines
	#FuncStdDev=lambda Keys_Values: (reduce(lambda x,y: x+y,map(lambda x: (x-FuncMean(Keys_Values))**2,Keys_Values))/float(len(Keys_Values)))**.5
	## Arithmetic Code for Standard Deviation (sq root of variance [measure of variability (spread\dispersion)])
	#StDev=(sum((Key_Day^2)-(len(Keys_Values))*(Mean^2) for Key_Day in Keys_Values)/len(Keys_Values))**0.5
	StDev=(sum((Key_Day-Mean)**2 for Key_Day in Keys_Values)/len(Keys_Values))**0.5 # means # numbers
	print("Daily StDev.S: "+str(Key_Day),StDev)

"""
wget https://learn.london.ac.uk/pluginfile.php/189728/mod_folder/content/0/200706hourly.txt

cat 200707hourly.txt | python mapper.py | sort | python reducer.py

20070701-20070719
18DaysEnteries=785807

20070701Enteries=429556
=MIN(B2:B42957)
Min	32
Max	115
Mean	70.71862785
StDev_P	11.66862018
StDev_S	11.66879037
StDevA	30.24284168
StDevPA	30.24248965
 """

"""
root@node:~# ls
200707hourly.txt  git  mapper.py  reducer.py
root@node:~# cat 200707hourly.txt | python mapper.py | sort | python reducer.py
('Daily Min: 20070701', 32.0)
('Daily Max: 20070701', 115.0)
('Daily Mean: 20070701', 70.71862785135056)
('Daily StDev: 20070701', 11.668620181190443)
('Daily Min: 20070702', 32.0)
('Daily Max: 20070702', 115.0)
('Daily Mean: 20070702', 70.9395780051151)
('Daily StDev: 20070702', 11.42449839793272)
('Daily Min: 20070703', 33.0)
('Daily Max: 20070703', 115.0)
('Daily Mean: 20070703', 72.7748518572048)
('Daily StDev: 20070703', 10.775145131164564)
('Daily Min: 20070704', 29.0)
('Daily Max: 20070704', 120.0)
('Daily Mean: 20070704', 73.9162407063197)
('Daily StDev: 20070704', 10.640547937161012)
('Daily Min: 20070705', 33.0)
('Daily Max: 20070705', 120.0)
('Daily Mean: 20070705', 74.60091011854729)
('Daily StDev: 20070705', 10.822513845267798)
('Daily Min: 20070706', 38.0)
('Daily Max: 20070706', 133.0)
('Daily Mean: 20070706', 75.04550619082302)
('Daily StDev: 20070706', 11.192606184103425)
('Daily Min: 20070707', 32.0)
('Daily Max: 20070707', 116.0)
('Daily Mean: 20070707', 75.8927368787738)
('Daily StDev: 20070707', 11.515439088473617)
('Daily Min: 20070708', 36.0)
('Daily Max: 20070708', 111.0)
('Daily Mean: 20070708', 76.51774047053998)
('Daily StDev: 20070708', 11.157227465279565)
('Daily Min: 20070709', 36.0)
('Daily Max: 20070709', 110.0)
('Daily Mean: 20070709', 75.99281122150789)
('Daily StDev: 20070709', 10.999190012631445)
('Daily Min: 20070710', 35.0)
('Daily Max: 20070710', 115.0)
('Daily Mean: 20070710', 74.95989140905509)
('Daily StDev: 20070710', 10.869943561233223)
('Daily Min: 20070711', 33.0)
('Daily Max: 20070711', 115.0)
('Daily Mean: 20070711', 72.97240273932682)
('Daily StDev: 20070711', 10.944897773689505)
('Daily Min: 20070712', 3.0)
('Daily Max: 20070712', 111.0)
('Daily Mean: 20070712', 72.12499271094525)
('Daily StDev: 20070712', 11.310119561067708)
('Daily Min: 20070713', 35.0)
('Daily Max: 20070713', 111.0)
('Daily Mean: 20070713', 71.83831640058055)
('Daily StDev: 20070713', 11.293579899562012)
('Daily Min: 20070714', 40.0)
('Daily Max: 20070714', 110.0)
('Daily Mean: 20070714', 73.13970374673251)
('Daily StDev: 20070714', 10.973087804624335)
('Daily Min: 20070715', 36.0)
('Daily Max: 20070715', 111.0)
('Daily Mean: 20070715', 73.85910952339462)
('Daily StDev: 20070715', 11.169989007109107)
('Daily Min: 20070716', 38.0)
('Daily Max: 20070716', 114.0)
('Daily Mean: 20070716', 74.33973407814727)
('Daily StDev: 20070716', 11.18677205943412)
('Daily Min: 20070717', 39.0)
('Daily Max: 20070717', 114.0)
('Daily Mean: 20070717', 74.87995037694436)
('Daily StDev: 20070717', 10.809281562106243)
('Daily Min: 20070718', 39.0)
('Daily Max: 20070718', 113.0)
('Daily Mean: 20070718', 75.74674272836116)
('Daily StDev: 20070718', 10.368264104751113)
('Daily Min: 20070719', 74.0)
('Daily Max: 20070719', 90.0)
('Daily Mean: 20070719', 80.97402597402598)
('Daily StDev: 20070719', 4.0611367673942205)
root@node:~#
 """